### ISSUE TITLE
feat request: Patch colorized git-diff style output

### ISSUE THREAD

**Issue by blacktop** [wI2L/jsondiff#18]
Would it be possible to represent the diffs similar to the way `git diff`s work?

**Comment by wI2L** [comment]
@blacktop This library generates a JSON Patch (RFC6902), which is a list of operations representing the differences between two JSON documents.

What you're asking for is outside the feature scope of this package.

You're probably looking for something like this, which doed what you described: https://github.com/andreyvit/json-diff

**Comment by wI2L** [comment]
@blacktop This library generates a JSON Patch (RFC6902), which is a list of operations representing the differences between two JSON documents.

What you're asking for is outside the feature scope of this package.

You're probably looking for something like this, which doed what you described: https://github.com/andreyvit/json-diff

**Comment by blacktop** [comment]
Thank you for those links! ❤️
