### ISSUE TITLE
adding Apply methods?

### ISSUE THREAD

**Issue by delaneyj** [wI2L/jsondiff#2]
It appears that https://github.com/evanphx/json-patch doesn't support the patches you are generating.  I really like the terse results of your patches and have validated that they are [valid](https://json-schema-validator.herokuapp.com/jsonpatch.jsp).  Given you are already parsing and looking for deltas, would it be possible to make some Apply and Revert functions in addition to patch generation?

**Comment by wI2L** [comment]
@delaneyj 
I'm surprised to hear that the `evanphx/json-patch` package doesn't work with some patch generated by `jsondiff`. Could you please provide an example ?

**Comment by delaneyj** [comment]
https://github.com/evanphx/json-patch/issues/142

Looks like root access via a `""` json pointer errors out.  I also looked at writing my own using gabs but [it has the same issue](https://github.com/Jeffail/gabs/issues/100) but a fix is incoming there.

**Comment by wI2L** [comment]
@delaneyj I think this issue is better fixed in evanphx/json-patch. I have no plans to extend the library to add support for JSON patch application, since the before-mentioned package works pretty well.
