### ISSUE TITLE
Issues related to array indexing.

### ISSUE THREAD

**Issue by btsunjin** [wI2L/jsondiff#27]
I want to compare two JSON files
base.json like this:

```json
{
  "data": [
    {
      "a": 2
    },
    {
      "x": 3
    },
    {
      "y": 4
    },
    {
      "b": 2
    }
  ]
}
```
current.json like this:
```json
{
  "data": [
    {
      "a": 2
    },
    {
      "b": 2
    },
    {
      "c": 2
    }
  ]
}
```
My code: 
```golang
func TestDiffJson(t *testing.T) {
        base :=  readJson(path)         // read json file as []byte
        current :=  readJson(path)    // read json file as []byte
	resp, _ := jsondiff.CompareJSON(base, current, jsondiff.LCS())
	fmt.Println(resp.String())
}
```
The result like this:
{"op":"remove","path":"/data/1"}
{"op":"remove","path":"**/data/1**"}
{"value":{"c":2},"op":"add","path":"/data/2"}

But I expect the result like this:
{"op":"remove","path":"/data/1"}
{"op":"remove","path":"**/data/2**"}
{"value":{"c":2},"op":"add","path":"/data/2"}

Why does the remove operation modify the array indices? This makes it very difficult for me to find the corresponding position in base.json.

**Comment by wI2L** [comment]
It's working as expected.

Take the list of operations that were generated and apply the operations sequentially to the original document. If you remove the array value at indice 1, then the value that was at indice 2 becomes the value at indice 1.

To then delete the original value at indice 2, we must now use the indice 1, like in the previous operation.

You can try it live on the [playground](https://jsondiff.wi2l.pw/) and https://jsonpatch.me/ for comparison.

**Comment by btsunjin** [comment]
Thanks! I understand. Maybe I'll use it in a different way.
